# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.
# Example:
# Input:
# s = "abcd"
# t = "abcde"
# Output:
# e
# Explanation:
# 'e' is the letter that was added.
# 思路很简单，用一个字典来保存出现过的字母，记录这个字母出现的次数，然后遍历第二个字符串的时候减去次数，多出来的那一个必定是刚插入进去的字母

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        lookup = {}
        for letter in s:
            if letter in lookup.keys():
                lookup[letter] += 1
            else:
                lookup[letter] = 1
        for letter in t:
            if letter in lookup.keys() and lookup[letter] > 0:
                lookup[letter] -= 1
            else:
                return letter
